<!DOCTYPE html>
<html>

    <head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Perez Chapel">
	<meta name="keywords" content="Perez Chapel">
	<meta name="author" content="Gad Ocansey">
	<!-- <base href="/"> -->

	<title>EagleApp | Dashboard</title>
	
	<!-- Icons -->
        <link rel="stylesheet" href="assets/fonts/ionicons/css/ionicons.min.css">
        <link rel="stylesheet" href="assets/fonts/font-awesome/fonts/font-awesome.min.css">
        <link rel="stylesheet" href="assets/styles/material-design-iconic-font.mine7ea.css">
	<!-- Plugins -->
        <link rel="stylesheet" href="assets/styles/plugins/c3.css">
        <link rel="stylesheet" href="assets/styles/plugins/waves.css">
        <link rel="stylesheet" href="assets/styles/plugins/perfect-scrollbar.css">

	<link rel="stylesheet" href="assets/scripts/buttons.dataTables.min.css">
	<!-- Css/Less Stylesheets -->
	<link rel="stylesheet" href="assets/styles/bootstrap.min.css">
	<link rel="stylesheet" href="assets/styles/main.min.css">
        <!--<link rel="stylesheet" href="assets/styles/materialadminb0e2.css"> -->

	 <style>
    #data-table-command  tr:hover{
        
        background-color: #FFFCBE;
    }
    #assesment  tr:hover{
        
        background-color: #FFFCBE;
    }
    #bill  tr:hover{
        
        background-color: #FFFCBE;
    }
</style>
	<script type="text/javascript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<script>
                    function inse(inco){
                    var curr=document.getElementById('sms');
                    curr.value=curr.value+"["+inco+"]"
                    }
</script>
<script language="javascript" type="text/javascript">
    function printDiv(divID) {
        //Get the HTML of div
        var divElements = document.getElementById(divID).innerHTML;
        //Get the HTML of whole page
        var oldPage = document.body.innerHTML;

        //Reset the page's HTML with div's HTML only
        document.body.innerHTML = 
          "<html><head><title></title></head><body>" + 
          divElements + "</body>";

        //Print Page
        window.print();

        //Restore orignal HTML
        document.body.innerHTML = oldPage;


    }
</script>
</head>