 
 				<!-- site logo -->
                                <p>&nbsp;</p> <p>&nbsp;</p>  
			 

			<!-- Site nav (vertical) -->
                        <nav class="site-nav clearfix" role="navigation">
				 
				<!-- navigation -->
				<ul class="list-unstyled clearfix nav-list mb15">
					 <?php require 'menu.php'; ?>
				</ul> <!-- #end navigation -->
			</nav>
                        <!-- nav-foot -->
			<footer class="nav-foot">
                            <p style="font-size: 8px">  &copy;<?php echo date("Y"); ?> <span>Perez Chapel | All rights reserved</span></p>
			</footer>