
	

	<!-- Dev only -->
	<!-- Vendors -->
     <script src="assets/scripts/vendors.js"></script>


	<script src="assets/scripts/plugins/screenfull.js"></script>
	<script src="assets/scripts/plugins/perfect-scrollbar.min.js"></script>
	<script src="assets/scripts/plugins/waves.min.js"></script>
        
	 
	<script src="assets/scripts/app.js"></script>
	<script src="assets/scripts/tables.init.js"></script>
        
        
