
	

	<!-- Dev only -->
	<!-- Vendors -->
        <script src="assets/scripts/vendors.js"></script>
        <script src="assets/scripts/plugins/d3.min.js"></script>
        <script src="assets/scripts/plugins/c3.min.js"></script>
        <script src="assets/scripts/plugins/screenfull.js"></script>
        <script src="assets/scripts/plugins/perfect-scrollbar.min.js"></script>
        <script src="assets/scripts/plugins/waves.min.js"></script>
        <script src="assets/scripts/plugins/jquery.sparkline.min.js"></script>
        <script src="assets/scripts/plugins/jquery.easypiechart.min.js"></script>
        <script src="assets/scripts/plugins/bootstrap-rating.min.js"></script>
        <script src="assets/scripts/app.js"></script>
        <script src="assets/scripts/index.init.js"></script>
